Raise required toolchain to Rust 1.82
This is required by bindgen 0.71, which is used by libsqlite3-sys 0.31.

    error: extern block cannot be declared unsafe
       --> target/debug/build/libsqlite3-sys-3da8b75ff8e55f52/out/bindgen.rs:521:1
        |
    521 | unsafe extern "C" {
        | ^^^^^^